### ISSUE TITLE
希望本地媒体库增加自动识别信息、按番剧分类、显示每话标题、删除文件功能

### ISSUE THREAD

**Issue by NatralMicsear** [xyoye/DanDanPlayForAndroid#103]
希望本地媒体库能像pc版一样，可以按番剧分类，可以切换显示每话标题，可以直接在媒体库删除本地文件。并希望能一键自动更新视频识别信息。

**Comment by Brianwind** [comment]
还有从app连接到电脑的媒体库时，也希望支持这个功能
