### ISSUE TITLE
无法访问本地webdav服务器？

### ISSUE THREAD

**Issue by Gokou-Ruri** [xyoye/DanDanPlayForAndroid#104]
**Bug描述**
无法在弹弹Play里访问通过 [webdav-aliyundriver](https://github.com/zxbu/webdav-aliyundriver) 架设的本地webdav服务器，提示“连接失败:Not a valid DAV response”。（通过fx文件管理器可以正常访问该webdav）

**屏幕截图**
![Screenshot_20210919-001324_图库](https://user-images.githubusercontent.com/26711804/133895370-53ead72c-370e-4c4d-855c-1150a1ea24cf.png)

**设备信息（请回答下列问题）：**
 - Custom ROM：[Evolution X 5.9.2]
 - OS：[Android 11]
 - 程序版本：[4.0.4]

**附加内容**
[webdav-aliyundriver](https://github.com/zxbu/webdav-aliyundriver) 是通过termux自带的openjdk运行的。

**Comment by xyoye** [comment]
不能访问原因是：访问webdav-aliyundriver架设的webdav服务器时，响应返回的xml数据格式不够规范，而弹弹使用的webdav库是默认以严格模式解析响应的xml数据。

为了避免在其它webdav服务器也会有这种问题，APP新增加了数据解析模式切换的选项按钮，见[release-4.0.4.1](https://github.com/xyoye/DanDanPlayForAndroid/releases/tag/release-v4.0.4.1)
