### ISSUE TITLE
安卓端打开媒体库文件夹闪退

### ISSUE THREAD

**Issue by Kus-A** [xyoye/DanDanPlayForAndroid#105]
**Bug描述**
打开本地媒体库选择视频所在文件夹会闪退（文件夹内视频过多的情况下）

**如何重现**
我是下载了妖精的尾巴总共277集到手机里
选择前175集的文件夹会闪退，后176-277则不会，将前175集分开到两个文件夹内并不会闪退

**希望的正确行为**
虽然可以自己分散一下，但有空的话希望能看看，增加一下单文件夹读取文件上限，不过我遇到的情况也比较特殊了

**设备信息（请回答下列问题）：**
 - 设备：小米11U
 - OS：Android 11
 - 程序版本：4.0.4

**Comment by xyoye** [comment]
根据收集到的崩溃日志，我这边修复了，可以下最新的测试包看看：[dandanplay-v4.0.5-beta](https://github.com/xyoye/DanDanPlayForAndroid/releases/tag/dandanplay-v4.0.5-beta)

**Comment by Kus-A** [comment]
测试包试过了，没问题，幸苦了
