### ISSUE TITLE
群晖smb获取文件列表失败

### ISSUE THREAD

**Issue by Mateoust** [xyoye/DanDanPlayForAndroid#106]
**Bug描述**
设备是群晖，使用smb登录群晖。无法查看文件列表。#recycle这个文件夹在群晖中是开启了回收站功能有的。然后查看另外一个共享文件夹。可以正常访问。正常播放。而这个共享文件夹没有开启回收站功能。所以功能正常。于是将不能查看列表的共享文件夹里的#recycle删除。可以正常访问。

**希望的正确行为**
因为不知道删除#recycle会导致什么，所以希望不删除#recycle的情况下可以正常获取列表

**报错截图**
![Screenshot_2021-11-24-00-58-27-779_com.xyoye.dand.jpg](https://i.loli.net/2021/11/24/bo4micuOFErv8ya.jpg)

**设备信息**
 - 设备：小米8 UD
 - OS：Android 10
 - 程序版本：4.0.4

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
