### ISSUE TITLE
希望手机端对可以对弹幕、字幕进行更进一步的操作

### ISSUE THREAD

**Issue by wzxyisme** [xyoye/DanDanPlayForAndroid#107]
**您的功能请求是否与一个问题有关？请说明。**
在使用手机端看远程媒体库里的视频时，我总觉得不大舒服，弹幕换源只能换本地的文件不能再次更换网上的弹幕源，手机端不能更换PC端的视频绑定的弹幕库，有时拖拉进度条弹幕直接没了，PC端新加入媒体库的部分番剧手机端看时没有弹幕，也没办法刷新
 字幕不能手动搜索，自动搜索不好使，自动播放某些番剧时明明PC端就只有中文字幕文件，在手机端却只能选择英文，还有PC端下好字幕到视频同一目录不能及时生效，手动选择PC端字幕文件重启PC端，扫描文件改动，重启手机端清除手机端缓存都不能使之立即生效。
还有请问PC端有计划登录Linux平台吗？

**描述你所想要的解决方案**
1.播放远程媒体库里的视频时可以手动选择PC端文件夹里的字幕。
2.手机端可以重新搜索绑定PC端视频的弹幕，且同步到PC端
3.可以用"弹幕开关"或者独立按钮来刷新弹幕。
4.在PC端加入新字幕文件后可以使用"扫描文件改动"使字幕在PC端自动配对生效，而不是一集一集的手动选择。
5.加快PC端字幕在远程媒体库中的生效速度

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要的描述。

**附加内容**
在这里加上其他所有关系的内容

**Comment by Gokou-Ruri** [comment]
补充：希望可以指定（ass）字幕的字体，即忽略ass内指定字体，使用用户指定的字体。

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
