### ISSUE TITLE
在全面屏设备上，字幕与画面脱离

### ISSUE THREAD

**Issue by ghost** [xyoye/DanDanPlayForAndroid#108]
**Bug描述**
在全面屏播放视频，视频下面的字幕（非视频内嵌字幕）上一半在画面上，下一半在黑色，看番剧的时候向下面看字幕感觉非常不和谐。

**屏幕截图**
![Screenshot_20211129_011002_com.xyoye.dandanplay_edit_34767699052829.jpg](https://user-images.githubusercontent.com/59795360/143778697-3c0a5679-5e80-4b1f-b35e-2ad2e34da4e0.jpg)

**希望的正确行为**
希望能够允许用户修改字幕距离屏幕底端的位置。

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
