### ISSUE TITLE
【BUG】播放搜资源里面的文件时 无法选择弹幕

### ISSUE THREAD

**Issue by 850710247liu** [xyoye/DanDanPlayForAndroid#110]
点击字幕组磁链后 播放资源直接进入播放器 没有选择弹幕的提示
![Screenshot_20211213_024136_com.xyoye.dandanplay.jpg](https://user-images.githubusercontent.com/59795360/145725197-f44b8317-9c89-4735-aeda-803ae88c3c82.jpg)

**Comment by xyoye** [comment]
APP首页->我的->播放器设置->弹幕->【外部视频】展示选择弹窗

**Comment by 850710247liu** [comment]
实测预发行版本4.0.5不弹出选择弹幕
4.0.4弹出
设备：matepad11

**Comment by xyoye** [comment]
4.0.5版本将更改弹幕加载逻辑，这方面还没处理完

**Comment by 850710247liu** [comment]
好的 辛苦作者大大啦
