### ISSUE TITLE
希望在弹幕路径换源中可以换网络弹幕

### ISSUE THREAD

**Issue by ghost** [xyoye/DanDanPlayForAndroid#111]
点击右侧的换源 目前只能换本地弹幕 希望能换网络弹幕 出现那个弹幕选择
![Screenshot_20211213_024411_com.xyoye.dandanplay.jpg](https://user-images.githubusercontent.com/59795360/145725324-007287e3-f373-49af-aad1-6e9c4db37678.jpg)

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
