### ISSUE TITLE
不支持http的WEBDAV？

### ISSUE THREAD

**Issue by Gokou-Ruri** [xyoye/DanDanPlayForAndroid#112]
**Bug描述**
通过 [webdav-aliyundriver](https://github.com/zxbu/webdav-aliyundriver) 
项目创建的WEBDAV服务器添加到弹弹Play安卓版中无法访问，弹弹Play提示`Not a valid DAV response`，弹弹Play只能使用https吗？
![Screenshot_20211217-013737_图库](https://user-images.githubusercontent.com/26711804/146421884-04a4a648-6d6e-47da-bb2a-1e088fa71e1c.png)

**Comment by xyoye** [comment]
支持的，编辑wabdav账号时，数据解析模式选择宽松模式

**Comment by Gokou-Ruri** [comment]
> 支持的，编辑wabdav账号时，数据解析模式选择宽松模式

谢谢！用来要安装测试版才有这个选项，现在能够访问了。
但部分文件夹进不去，下图除了画圈的文件夹，其它的都打不开。
![Screenshot_20211221-033414_弹弹play_概念版_1](https://user-images.githubusercontent.com/26711804/146822799-92b0828a-73d8-46a6-ba9c-7abbd38302ca.png)
![Screenshot_20211221-033347_弹弹play_概念版](https://user-images.githubusercontent.com/26711804/146822856-7f9fedc8-654d-4bd4-acc7-ff8b340db126.png)


顺便请教一下部分分集视频的文件名字体较小是什么原因？例如这个样子的。
![Screenshot_20211221-033917_弹弹play_概念版](https://user-images.githubusercontent.com/26711804/146823186-bb574286-131c-4fd8-8440-455c3b632371.png)

**Comment by xyoye** [comment]
有可能是特殊导致的，我这边会排查确认一下
文字的的话，是由于采用了文字大小自适应的方案导致的，但由于不影响功能，所以会排在比较后面修复

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
