### ISSUE TITLE
一个想法——通过浏览器调用弹弹Play

### ISSUE THREAD

**Issue by MagmaBlock** [xyoye/DanDanPlayForAndroid#113]
**描述你所想要的解决方案**
挺多播放器/软件都有此类功能，比如当在浏览器中点击某些自定义协议的链接时，
浏览器会调用当前设备上已经安装的软件
演示页面：https://s-sh-2164-assets.oss.dogecdn.com/LavaAnime/Test/test.html

这种调用方式挺方便的，如果也能给弹弹加一个，应该看番会有更多新玩法
调用时要是能同时给出相关的 `episodeId` 之类的值，让播放器自动匹配弹幕库(以及手动选配第三方？)，体验应该会更好x
这个建议我看看一会也给Windows端那边发一个，如果能实现各端通用也挺重要的

**描述您考虑过的替代方案**
如同上面的演示界面一样，电脑端的PotPlayer，安卓端的VLC是有这种功能的
在浏览器里一点就能直接跳到播放器

**附加内容**
咱这边在开发一个在线番剧库，为了达到最佳的播放体验，不打算转码二压。因此需要在线串流很多格式，浏览器播放肯定是支持不了了。因为我也用弹弹Play的电脑和安卓挺长时间了，现在的半成品只能手动复制视频链接，然后再粘到弹弹Play里，并且手动搜弹幕。感觉如果能直接把弹弹Play用作播放器就很不错，而且还能支持弹幕

**Comment by MagmaBlock** [comment]
> 可以在html网页加入 `<a href='intent:https://视频链接#Intent;package=com.xyoye.dandanplay;end'>点击我跳转弹弹play播放</a> `

太方便了，试了一下真的可以，看起来像是 Android 的 API

**Comment by Wuming-HUST** [comment]
> 可以在html网页加入 `<a href='intent:https://视频链接#Intent;package=com.xyoye.dandanplay;end'>点击我跳转弹弹play播放</a> `

请教一下，在 Windows 上 弹弹play 有类似的 uri 么，我试了 `dandanplay://` 和 `弹弹play://` 都不行，查注册表，URI Protocol 就写的是 `弹弹play`，不过它的参数没加 URL 前缀，我估计不是。

**Comment by MagmaBlock** [comment]
@Wuming-HUST 可以参考此处：
https://github.com/MagmaBlock/LavaAnimeLibWeb/blob/03d77df9778d8f9d53f3503990a28696c7a83f2f/src/components/Anime/LocalPlayer/LocalPlayerIcons.vue#L141

**Comment by MagmaBlock** [comment]
@Wuming-HUST 
ddplay:文件的url|filePath=文件名
然后整个进行URL编码，结果的链接放进a标签的herf

**Comment by Wuming-HUST** [comment]
十分感谢，我主要是通过 Alist 跳转弹弹play，使用了 Alist 的 External previews，可以直接使用 Alist url 即可跳转。

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
