### ISSUE TITLE
希望设置中增加默认简体弹幕

### ISSUE THREAD

**Issue by ghost** [xyoye/DanDanPlayForAndroid#114]
播放视频默认使用简体化弹幕，就是默认这个

![Screenshot_20220103_201504_com.xyoye.dandanplay_edit_69417708110705.jpg](https://user-images.githubusercontent.com/59795360/147929459-ded98f64-142a-421e-b53b-902d31fb13d3.jpg)

在设置中增加一个选项达成直接播放默认选简体弹幕的效果，辛苦了

**Comment by xyoye** [comment]
请查看最新版
