### ISSUE TITLE
MKV视频未正确显示字幕

### ISSUE THREAD

**Issue by SongJF** [xyoye/DanDanPlayForAndroid#117]
**Bug描述**
播放内嵌的字幕的MKV视频，似乎读取到字幕文件，但是屏幕上未正确显示

**如何重现**
1. 下载mkv视频(地址: magnet:?xt=urn:btih:f1753106680d77e73ed2c43209344592eb8d6187)
2. 播放视频
3. 检查字幕设置

**希望的正确行为**
正确显示字幕

**屏幕截图**
1. 同时间截屏
- DanDanPlay
![dandan_player](https://s2.loli.net/2022/02/09/XaOG9UT67PdfEsp.jpg)
- MX Player
![mx_player](https://s2.loli.net/2022/02/09/v37NrbYjqQXSUpn.jpg)
2. 字幕检查
- 似乎已经正确加载字幕文件
![check_sub](https://s2.loli.net/2022/02/09/d6V4hXWf2vp8zuQ.jpg)

**设备信息（请回答下列问题）：**
 - 设备：荣耀 30 Pro+
 - OS：鸿蒙2.0.0
 - 程序版本：4.0.4

**附加内容**
NaN

**Comment by FFishG** [comment]
@SongJF 我遇到了同样的问题，外挂字幕同样也会出现无法显示的现象，经过排查之后发现是无法显示srt格式字幕文件的问题，可通过MKVExtractGUI提取字幕文件查看格式，如果内挂字幕格式为ass则可以正常显示。

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
