### ISSUE TITLE
是否可以新增方向键和确认键使用安卓app的功能

### ISSUE THREAD

**Issue by TimeToGone** [xyoye/DanDanPlayForAndroid#118]
突发奇想在电视上访问电脑的媒体库进而播放视频和弹幕，但在app的“媒体库”页面利用遥控器的上下左右方向键和确认键，无法选择并添加远程媒体库，也无法使用其他功能。就想问问是否可以实现。

是否还有其它方法方案可以实现在电视上访问电脑媒体库的视频呢？

PS：在电视上用网页访问电脑媒体库再播放视频的操作已经试过，体验不好，毕竟遥控器上只有方向键和确认键能进行一些操作。

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
