### ISSUE TITLE
无法连接webdav

### ISSUE THREAD

**Issue by mouzi3102** [xyoye/DanDanPlayForAndroid#119]
![Screenshot_20220303_123310](https://user-images.githubusercontent.com/46465612/156496902-808d8b73-02bf-4d76-b533-93d76ec52e31.jpg)
![Screenshot_20220303_123324](https://user-images.githubusercontent.com/46465612/156496911-1c5d49c2-21a9-4347-9498-b35b3c25cec7.jpg)
无论怎么设置，都无法连接webdav，其他播放器都正常，请问作者大大怎么解决呀

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
