### ISSUE TITLE
中途加载弹幕，没有匹配时间戳

### ISSUE THREAD

**Issue by JeffersonQin** [xyoye/DanDanPlayForAndroid#121]
**Bug描述**
在播放视频到一般的时候再加载弹幕（网络搜索），加载完毕后显示的弹幕时间没有经过调整，比方说已经看到了20分钟，加载完弹幕，看到的弹幕就会是0分钟的

**如何重现**
已测试：弹弹play媒体库、ftp媒体库；网络弹幕

**希望的正确行为**
对你所希望程序应作出的正确行为（即没有bug时的行为）的简明扼要的描述。

**屏幕截图**
如果适用的话，请添加一些屏幕截图以帮助解释您的问题。使用sm.ms图床服务会是一个好主意。

**设备信息（请回答下列问题）：**
 - 设备：MIX 4
 - OS: MIUI 12.5
 - 程序版本：4.0.5

**附加内容**
在这里加上其他所有有关该Bug的内容。

**Comment by xyoye** [comment]
请查看最新版
