### ISSUE TITLE
smb共享访问错误。

### ISSUE THREAD

**Issue by tom2201** [xyoye/DanDanPlayForAndroid#126]
**Bug描述**
访问smb共享文件夹内部如果存在aquota.user 和 aquota.group 磁盘配额文件报提示访问aquota.user失败无法正常显示。

![f0c00171fe9243d0c55c85976260726](https://user-images.githubusercontent.com/97517069/168205089-ff8ccac0-de58-41b3-ac99-103879a97db1.jpg)

**Comment by hathlife** [comment]
这个是只要扫描到smb权限不足的文件/路径就会失败报错，需要加入可以在扫描smb目录时自动跳过权限不足的文件/路径的功能

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
