### ISSUE TITLE
在手动切换深色模式后，文件夹和视频文件的名字是黑色字体导致看不见。

### ISSUE THREAD

**Issue by SouthThink** [xyoye/DanDanPlayForAndroid#127]
在手动切换深色模式后，文件夹和视频文件的名字是黑色字体导致看不见。
设置-深色模式-跟随系统-关 手动深色模式
打开本地媒体库后所有文件名字以及描述全为黑色，与背景融为一体。
设备：huawei nova 3i 系统：HarmonyOS2（安卓9）系统不自带深色模式
希望能把文件的名字也在暗黑模式下显示为白色。

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
