### ISSUE TITLE
webdav同目录下字幕文件无法识别

### ISSUE THREAD

**Issue by skyrim663** [xyoye/DanDanPlayForAndroid#129]
**Bug描述**
使用webdav挂载播放里面视频时，无法读取同目录下的外挂字幕

**如何重现**
重现该程序行为的步骤：
1. 到达视频所在目录位置
2. 点击播放
3. app只能显示当前目录下的视频文件，未显示字幕文件，点击播放没有字幕

**希望的正确行为**
APP能够识别同目录下的字幕文件

**设备信息（请回答下列问题）：**
 - OS：Android 10.0(Google)
 - 程序版本：dandanplay-v4.0.6

**附加内容**
希望APP能够识别同目录下的字幕文件

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
