### ISSUE TITLE
视频解析不正确，信息和视频文件对不上

### ISSUE THREAD

**Issue by SettingDust** [xyoye/DanDanPlayForAndroid#130]
**Bug描述**
视频信息指向文件不正确，播放也是错误的视频，API 的 JSON 是显示正确文件的（Hash 一致，看起来 DanDan API 有点问题）
https://pastes.dev/T8QKn0eDIc

**如何重现**
不确定，视频是动漫国的 BD

**希望的正确行为**
正常显示视频信息及对应视频

**屏幕截图**
![图片](https://user-images.githubusercontent.com/19922286/177692388-96210ab0-d2ec-4754-af51-e3c0d0d63844.png)

**设备信息（请回答下列问题）：**
 - 设备：iQOO Neo3，Android TV
 - OS：Android 11，9
 - 程序版本：4.0.6

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
