### ISSUE TITLE
访问远程媒体库时播放器内选集提示 资源不存在

### ISSUE THREAD

**Issue by CberYellowstone** [xyoye/DanDanPlayForAndroid#133]
![image](https://user-images.githubusercontent.com/37031767/179478279-5b9beec7-a9db-4ad0-b45f-b8101f82ec69.png)
![image](https://user-images.githubusercontent.com/37031767/179478302-ab1f829e-2fc5-4130-a658-c6404b57a5f3.png)

只有 访问远程媒体库才会如此
访问webdav时正常
且抛出该异常时概念版本身没发出任何包，个人猜测排除桌面版客户端方面问题（实际上在外面菜单选集能正常播放）

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
