### ISSUE TITLE
概念版访问 远程资源库 时，发出了多余的 /api/v1/comment/ 请求

### ISSUE THREAD

**Issue by CberYellowstone** [xyoye/DanDanPlayForAndroid#134]
为何说是多余的？
实测v4.0.6概念版即使成功请求到了 /api/v1/comment/，也还是会尝试自行匹配，直接无视 /api/v1/comment/ 返回的弹幕

P.S. 自行匹配是指：正在收集匹配所需信息中...

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
