### ISSUE TITLE
【功能请求】远程资源库 展示方式 增加可选项

### ISSUE THREAD

**Issue by CberYellowstone** [xyoye/DanDanPlayForAndroid#137]
详见 Pr #136 

目标效果：用户能在 当前 和 https://github.com/xyoye/DanDanPlayForAndroid/commit/64092b0eeb4eb5d1a5089219859d8346b4d4d5bd 两种展示方式间选择切换

@xyoye

**Comment by xyoye** [comment]
我认为没有没有必要，也不应该通过AnimeId进行分类。

1. 并不是所有视频都会包含AnimeId。以番剧为例，完整下载种子文件时，都会包含番剧的Preview、OP、SP等内容，这些是无法识别到AnimeId的，因此无法对此进行分类。

2. 不同番剧的AnimeId是不一样的，如刀剑神域第一季、第二季，两者的AnimeId也是不一样的，因此没有以AnimeId进行分类的必要。

3. 以树形目录展示文件夹可以与其它媒体库的展示形式统一

![Screenshot_2022-07-19-23-24-10-465_com xyoye dand](https://user-images.githubusercontent.com/23527777/179789948-3d68df48-4ebb-444b-a5f3-092b304f18ae.jpg)

![QQ图片20220719233806](https://user-images.githubusercontent.com/23527777/179791372-bc408125-b03b-4c21-ae50-f114609a1f87.png)

**Comment by CberYellowstone** [comment]
> 我认为没有没有必要，也不应该通过 AnimeId 进行分类。
> 
> 1. 并不是所有视频都会包含 AnimeId。以番剧为例，完整下载种子文件时，都会包含番剧的 Preview、OP、SP 等内容，这些是无法识别到 AnimeId 的，因此无法对此进行分类。
> 2. 不同番剧的 AnimeId 是不一样的，如刀剑神域第一季、第二季，两者的 AnimeId 也是不一样的，因此没有以 AnimeId 进行分类的必要。
> 3. 以树形目录展示文件夹可以与其它媒体库的展示形式统一

1. 我认为没有AnimeId的资源不应该被加入到 `远程媒体库`，这点在 桌面端DanDanPlay媒体库 以及 网页版远程媒体库 中表现均一致
2. 同一部番剧的不同季度等AnimeId不同时应当被分为两个，原因同上，参照桌面远程媒体库
3. 我认为当前与其他媒体库统一恰是最大的问题，FTP、SMB、WebDav都是文件相关协议，而远程媒体库协议并非文件协议，而是特有协议，含有大量与，以树形目录展示有违其协议性质。与其它平台的远程媒体库一致我认为是最好的方法

以上均个人观点
下图为v1媒体库首页
![image](https://user-images.githubusercontent.com/37031767/179807809-40107ac0-f262-4f42-a1f1-5ce9c7d8e595.png)

**Comment by CberYellowstone** [comment]
相似的请求在 #69 也有提及

**Comment by Sanlorng** [comment]
> 我认为没有没有必要，也不应该通过AnimeId进行分类。
> 
> 1. 并不是所有视频都会包含AnimeId。以番剧为例，完整下载种子文件时，都会包含番剧的Preview、OP、SP等内容，这些是无法识别到AnimeId的，因此无法对此进行分类。
> 
> 2. 不同番剧的AnimeId是不一样的，如刀剑神域第一季、第二季，两者的AnimeId也是不一样的，因此没有以AnimeId进行分类的必要。
> 
> 3. 以树形目录展示文件夹可以与其它媒体库的展示形式统一
> 
> ![Screenshot_2022-07-19-23-24-10-465_com xyoye dand](https://user-images.githubusercontent.com/23527777/179789948-3d68df48-4ebb-444b-a5f3-092b304f18ae.jpg)
> 
> ![QQ图片20220719233806](https://user-images.githubusercontent.com/23527777/179791372-bc408125-b03b-4c21-ae50-f114609a1f87.png)
> 
>  

目前树形目录的展示形式对用户的资源整理有一定的要求，即 不能将不同的AnimeteId动画文件放在同一层级，否则只显示episodeTitle，你根本不知道它是什么动画的资源文件。二，所用的文件夹只能使用用户自己看得懂的名字，如果直接下载（通常是罗马音的文件夹）则用户需要自己去重命名文件夹，不然不方便阅读

**Comment by xyoye** [comment]
> 目前树形目录的展示形式对用户的资源整理有一定的要求，即 不能将不同的AnimeteId动画文件放在同一层级，否则只显示episodeTitle，你根本不知道它是什么动画的资源文件（弹弹Play追番，下载的文件都是在同一个文件夹）。二，所用的文件夹只能使用用户自己看得懂的名字，如果直接下载（通常是罗马音的文件夹）则用户需要自己去重命名文件夹，不然不方便阅读


> 1. 我认为没有AnimeId的资源不应该被加入到 `远程媒体库`，这点在 桌面端DanDanPlay媒体库 以及 网页版远程媒体库 中表现均一致


好的，我想我理解为什么需要这种展示方式了。增加以AnimeId分类作为展示的方案是可行的，会考虑在4.0.7中开发。

**Comment by CberYellowstone** [comment]
> > 目前树形目录的展示形式对用户的资源整理有一定的要求，即 不能将不同的 AnimeteId 动画文件放在同一层级，否则只显示 episodeTitle，你根本不知道它是什么动画的资源文件（弹弹 Play 追番，下载的文件都是在同一个文件夹）。二，所用的文件夹只能使用用户自己看得懂的名字，如果直接下载（通常是罗马音的文件夹）则用户需要自己去重命名文件夹，不然不方便阅读
> 
> > 1. 我认为没有 AnimeId 的资源不应该被加入到 `远程媒体库`，这点在 桌面端 DanDanPlay 媒体库 以及 网页版远程媒体库 中表现均一致
> 
> 好的，我想我理解为什么需要这种展示方式了。增加以 AnimeId 分类作为展示的方案是可行的，会考虑在 4.0.7 中开发。

![image](https://user-images.githubusercontent.com/37031767/179882634-1a21feb3-3218-48ae-a9b0-1345e4991d39.png)

这种效果即为按AnimeId分类（此处是我使用自定义后端改变了API中的Path，强行进行AnimeId分类）
