### ISSUE TITLE
【功能请求】希望增加smb对非标端口的支持

### ISSUE THREAD

**Issue by kafuuchino-s** [xyoye/DanDanPlayForAndroid#141]
**您的功能请求是否与一个问题有关？请说明。**
在使用smb媒体库时，只能连接默认的445端口的smb，不支持非标端口。
使用非标端口能绕过运营商isp对445端口的封锁，实现公网ip访问smb媒体库

**描述你所想要的解决方案**
添加smb媒体库时，能自定义端口

谢谢！

**Comment by tiiime** [comment]
题外话 smb 放到公网貌似有安全问题。

**Comment by kafuuchino-s** [comment]
> 题外话 smb 放到公网貌似有安全问题。

加了密码也会有安全问题吗？

**Comment by tiiime** [comment]
> > 题外话 smb 放到公网貌似有安全问题。
> 
> 加了密码也会有安全问题吗？

抓包并计算密码的文章，看起来 SMB 的认证不是很强  

- https://www.gushiciku.cn/pl/2H6U
- https://www.jianshu.com/p/5e1fc569463b

**Comment by hihi427** [comment]
没啥重要东西  安全什么的 无所谓吧   
希望把选择权交给用户  提供非默认端口smb支持 谢谢!
