### ISSUE TITLE
代码里调用的Xunlei SDK导致一些资源无法播放

### ISSUE THREAD

**Issue by sohowj** [xyoye/DanDanPlayForAndroid#144]
**Bug描述**
以下链接无法播放，提示”资源无法播放，请更换其它资源“：
magnet:?xt=urn:btih:V52MMCDEHIII2MMHSXWAXGVUCSIG4C4D

**如何重现**
[重现该程序行为的步骤：]
1. 搜索”异世界舅舅 04“
2. 点击搜索结果页里的【喵萌奶茶屋】07月新番[异世界舅舅/Isekai Ojisan][04][720p]
3. 点击播放

**希望的正确行为**
应该能正常播放

**附加内容**
经过调试，是调用的Xunlei SDK引起的。上面的 magnet 链接，其它软件可以正常下载，弹弹Play也成功下载到了torrent文件到
/storage/emulated/0/Android/data/com.xyoye.dandanplay/files/torrent/V52MMCDEHIII2MMHSXWAXGVUCSIG4C4D.torrent
并且这个 torrent 文件也可以用其它下载工具打开，说明 torrent 下载成功。

但是代码执行 ThunderManager.torrent2PlayUrl() 时失败。
用迅雷客户端打开上述 torrent 文件，迅雷提示：应版权方要求，无法下载该文件。因此应该是Xunlei SDK引起的。

**Comment by xyoye** [comment]
Xunlei SDK的功能实现都是封装SO库中，无法了解具体细节，也没法进行修改，所以这个问题暂时无解。除非更换在线播放的实现方式，但目前没有更好的方案，所以不会是近期考虑的问题。
