### ISSUE TITLE
打开主界面提示Fail to connect to api.acplay.net/127.0.0.2:443，应用无法使用

### ISSUE THREAD

**Issue by alanplateau** [xyoye/DanDanPlayForAndroid#146]
打开主界面提示Fail to connect to api.acplay.net/127.0.0.2:443，应用无法使用

**屏幕截图**
如果适用的话，请添加一些屏幕截图以帮助解释您的问题。使用sm.ms图床服务会是一个好主意。
![Screenshot_2022-08-19-22-03-16-206_com xyoye dand](https://user-images.githubusercontent.com/48021096/185637455-61716f0f-aad2-4e3b-961e-4bb2addceae4.jpg)

**设备信息（请回答下列问题）：**
 - 设备：Redimi K40
 - OS： MIUI 12.5.19
 - 程序版本：最先在4..0.14，后更新至4.0.16和4.0.15也无法解决，但4.0.14已经用了很久之前都没问题

。

**Comment by LeenDenVan** [comment]
现在电脑版也无法连接到官方api，应该是弹弹play开放平台出的问题，因为我现在打不开这个网页[弹弹play开放平台](https://api.acplay.net/swagger)

**Comment by Sanlorng** [comment]
[服务器故障了](https://mp.weixin.qq.com/s/GJJcAhvcUxGv1vBz9BiT5w)
