### ISSUE TITLE
可以添加半屏和精简弹幕的功能吗？

### ISSUE THREAD

**Issue by zzgit00** [xyoye/DanDanPlayForAndroid#152]
**您的功能请求是否与一个问题有关？请说明。**
要是弹幕太多的话还是会影响观看体验的，但是也不能一点弹幕也没有，所以还是希望能添加半屏和精简弹幕。

**描述你所想要的解决方案**
类似于b站的弹幕模式设置。

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
