### ISSUE TITLE
Not showing video by default subtitle ?

### ISSUE THREAD

**Issue by waqasyousafy** [xyoye/DanDanPlayForAndroid#153]
I have played a movie that have english subtitle . Your player with ijk selection not showing the subtitle . Until i download srt file and then add manually . Other players are doing fine by showing movie bydefault synced subtitle .

**Comment by waqasyousafy** [comment]
Please help and respond me

**Comment by xyoye** [comment]
Sorry, I haven't paid attention to the issue recently

Among the three playback cores of this player, the degree of support for subtitles is different. I suggest changing the core of the player, such as the VLC core.

**Comment by waqasyousafy** [comment]
xyoye i am adding subtitles to my existing video player using ijk videoplayer  . My new requirement is to add subtitles in it . So , could you help me out in this . Thank You in advance .

**Comment by xyoye** [comment]
I'm not sure if I understand correctly, you mean in your player project, the ijk kernel can't display subtitles?

If so, I recommend implementing the parsing and playback of subtitle files yourself instead of relying on the IJK kernel.
The reason are:
1. The subtitle formats supported by the ijk kernel are limited
2. The ijk kernel does not support subtitles of picture type
3. ijk kernel does not support adding external barrage

If you still insist on using the IJK kernel, then you can get the subtitle output of the video through setOnTimedTextListener

**Comment by AkiSakurai** [comment]
Stock ijkplayer embedded a slim version of ffmpeg that do not contains decoder for subrip subtitle. 

You have build ffmpeg yourself if you want more codecs.

**Comment by waqasyousafy** [comment]
I have added subtitle with setOnTimedTextListener  with video built in subtitle to show . Now I have to embed with external subtitle . I have seen your player support the external subtitle can you guide me on this . How this can be achieved.

**Comment by xyoye** [comment]
> I have added subtitle with setOnTimedTextListener with video built in subtitle to show . Now I have to embed with external subtitle . I have seen your player support the external subtitle can you guide me on this . How this can be achieved.

From this project, the implementation of external subtitles is mainly divided into two parts

The first part is parsing, which refers to reading the time and subtitle content in the subtitle file into an object. The code for processing this part in the project is in the [ExternalSubtitleManager](https://github.com/xyoye/DanDanPlayForAndroid/blob/master/player_component/src/main/java/com/xyoye/subtitle/ExternalSubtitleManager.kt).

Another part of the display refers to reading the appropriate subtitle content according to the video playback progress, and displaying it to the View. The code of this part of the content is in [SubtitleTextView](https://github.com/xyoye/DanDanPlayForAndroid/blob/master/player_component/src/main/java/com/xyoye/player/controller/subtitle/SubtitleTextView.kt).

**Comment by waqasyousafy** [comment]
I have tested with single embed subtitle it is working fine but when i use video with multiple subtitle it crashes with native c logs.  how can i support multi subtitle (embeded)
