### ISSUE TITLE
倍速播放时弹幕会加速但还是会逐渐落后

### ISSUE THREAD

**Issue by guidenhanyue** [xyoye/DanDanPlayForAndroid#154]
安卓4.0.7版bug
内核选EXO或VLC，倍速播放时：
4倍速时弹幕的时间轴和视频时间轴精确对应。
1.2、1.24、1.28、1.32等倍速时弹幕时间轴会加速，但是还是会逐渐落后于视频时间轴，一般播放3、4分钟后会落后10秒左右

**Comment by xyoye** [comment]
#73
