### ISSUE TITLE
希望可以加载串流视频的外挂字幕

### ISSUE THREAD

**Issue by tianjiaoshanzai** [xyoye/DanDanPlayForAndroid#172]
**Is your feature request related to a problem? Please describe.**
在串流Jellyfin平台的视频时，无法加载外挂字幕

同目录文件形如：File.mkv  
                             File.chs&jpn.ass
通过MX播放器串流可以正常加载

**Describe the solution you'd like**
希望串流时可以加载外挂字幕

**Describe alternatives you've considered**
字幕下载到本地指定目录自动识别同文件名加载

**Additional context**
Not any more

**Comment by xyoye** [comment]
本地外挂字幕选取加载问题已解决，预计下版本更新
