### ISSUE TITLE
使用ijkplayer内核时，无法加载内嵌字幕

### ISSUE THREAD

**Issue by hiliving** [xyoye/DanDanPlayForAndroid#174]
**Bug描述**
使用ijkplayer内核时，无法加载内嵌字幕，setOnTimedTextListener里没有字幕信息的回调。

**如何重现**
重现该程序行为的步骤：
这里是测试播放地址。
http://www.0bt0.com/mv/35314632.html?url=soupian.one

**希望的正确行为**
应该是可以加载字幕的，例如我使用GSYVideoPlayer里的ijk的so可以正常加载字幕。

**设备信息（请回答下列问题）：**
 - 设备：华为P30 pro
 - OS：鸿蒙3.0
 - 程序版本：4.0.8

**Comment by RikkaBlue** [comment]
也有同样问题，VLC 正常但是不能截图

**Comment by xyoye** [comment]
> **Bug描述** 使用ijkplayer内核时，无法加载内嵌字幕，setOnTimedTextListener里没有字幕信息的回调。
> 
> **如何重现** 重现该程序行为的步骤： 这里是测试播放地址。 http://www.0bt0.com/mv/35314632.html?url=soupian.one
> 
> **希望的正确行为** 应该是可以加载字幕的，例如我使用GSYVideoPlayer里的ijk的so可以正常加载字幕。
> 
> **设备信息（请回答下列问题）：**
> 
> * 设备：华为P30 pro
> * OS：鸿蒙3.0
> * 程序版本：4.0.8

我下载了链接中的第一个资源中的视频，发现不输出字幕是由于ijk不存在id为96264的编解码器，即srt字幕的编解码器

我这边尝试使用了GSYVideoPlayer中的so库，以及直接修改GSYVideoPlayer代码中的播放地址，但在setOnTimedTextListener中均未发现有字幕输出

如果你那边播放时可以输出字幕，请提供一个最小示例，我将以此为参考改进项目

**Comment by xyoye** [comment]
> 也有同样问题，VLC 正常但是不能截图 #145 似乎是字幕格式的问题，但是目前就是没办法兼得截图和字幕。
> 
> 不过 VLC 渲染器不支持截屏是什么原因呢？ libvlc 是有相关 api 的呀 [libvlc_video_take_snapshot](https://videolan.videolan.me/vlc/group__libvlc__video.html#ga9b0a3870ce962aa0358050b2d5a59143) VLC ANDROID 也有

截屏问题有解决方案，参考播放记录中视频图片，但目前尚未实现

另外，此问题与主题无关，建议新建issue

**Comment by hiliving** [comment]
> > **Bug描述** 使用ijkplayer内核时，无法加载内嵌字幕，setOnTimedTextListener里没有字幕信息的回调。
> > **如何重现** 重现该程序行为的步骤： 这里是测试播放地址。 http://www.0bt0.com/mv/35314632.html?url=soupian.one
> > **希望的正确行为** 应该是可以加载字幕的，例如我使用GSYVideoPlayer里的ijk的so可以正常加载字幕。
> > **设备信息（请回答下列问题）：**
> > 
> > * 设备：华为P30 pro
> > * OS：鸿蒙3.0
> > * 程序版本：4.0.8
> 
> 我下载了链接中的第一个资源中的视频，发现不输出字幕是由于ijk不存在id为96264的编解码器，即srt字幕的编解码器
> 
> 我这边尝试使用了GSYVideoPlayer中的so库，以及直接修改GSYVideoPlayer代码中的播放地址，但在setOnTimedTextListener中均未发现有字幕输出
> 
> 如果你那边播放时可以输出字幕，请提供一个最小示例，我将以此为参考改进项目

抱歉刚看到，这个问题我通过重新编译ijk并加载所有解码器解决了。
