### ISSUE TITLE
4.0.9测试版，无法显示中文名文件

### ISSUE THREAD

**Issue by chisaki0000** [xyoye/DanDanPlayForAndroid#176]
Bug描述：
dandanplay_v4.0.9_universal-beta，使用SMB媒体库时，共享文件夹内无法显示中文名称的文件（文件名如果有空格也会不显示），将文件名改为英文才能显示

设备信息：
 - 设备：SONY X90J（电视）
 - OS：Android 10.0

**Comment by xyoye** [comment]
已修复：[74826ba](https://github.com/xyoye/DanDanPlayForAndroid/commit/74826ba2ee93acb4cafe8df55fccb9a942eeb4ac)
