### ISSUE TITLE
smb 连接 服务器不显示中文文件夹

### ISSUE THREAD

**Issue by hihi427** [xyoye/DanDanPlayForAndroid#177]
**Bug描述**
smb非标准端口连接到远程服务器
无法显示文件夹名为中文的文件夹   文件名里有符号的也不显示 
后来发现不只是文件夹名, 文件名里有符号或者有中文 也显示不出来

**如何重现**
重现该程序行为的步骤：
1. 添加smb服务器
2. smb服务器创建中文名文件夹
3. 客户端连接到服务器
4. 错误出现 中文的文件夹不显示 其他文件夹 能看到

**希望的正确行为**
正常显示smb文件夹内的文件

**设备信息（请回答下列问题）：**
 - 设备：小米 13Ultra
 - OS：[MIUI14]
 - 程序版本：[4.0.9 beta]

**Comment by xyoye** [comment]
#176
