### ISSUE TITLE
由alist挂载的webdav无法被挂载

### ISSUE THREAD

**Issue by ZZZ-zero** [xyoye/DanDanPlayForAndroid#179]
如图，我于服务器上由alist挂载的夸克网盘，在应用中仍然报错Not a valid DAV response
![84b56310768b4a2765a861abcf22bb6](https://github.com/xyoye/DanDanPlayForAndroid/assets/30883525/b5411f0d-a505-483a-96fc-c29134ffe17e)

**Comment by xyoye** [comment]
Alist文档中有说明，使用WebDav时，其Url格式应为：http[s]://domain:port/dav/

截图中的链接访问得到的结果是html页面，不是WebDav响应，所以无法解析

**Comment by ZZZ-zero** [comment]
好的，已成功解决
