### ISSUE TITLE
电视上旧版弹弹无法去掉更新提示

### ISSUE THREAD

**Issue by wjz2001** [xyoye/DanDanPlayForAndroid#180]
**Bug描述**
弹弹的更新提示在手机上显示很正常，有退出按钮；但在电视盒子上更新提示就变成了一个超出画面的横幅，不管按什么键都没有反应。
我这边4.09的三个播放器都非常难用，只有旧版本的比较好用，但因为这个更新提示导致我无法使用旧版。

**如何重现**
重现该程序行为的步骤：
1. 打开旧版弹弹，比如4.08
2. 等待更新提示出现

**希望的正确行为**
优化操作和显示，使弹弹在电视盒子上也能正常显示更新提示，这样退出和更新都比较方便。

**设备信息（请回答下列问题）：**
 - 设备：HK1 BOX
 - OS：Android 9.0
 - 程序版本：4.08

**Comment by xyoye** [comment]
收到，这边会修复更新弹窗的样式问题。但是在旧版本上只能通过升级版本才能避免提示更新弹窗。

另外，问题中说的4.0.9播放器难用可以新开issue具体说说是哪些方面有问题。

**Comment by xyoye** [comment]
4.1.0已修复
