### ISSUE TITLE
4.0.9电视端无法加载弹幕

### ISSUE THREAD

**Issue by scarletfax** [xyoye/DanDanPlayForAndroid#183]
**Bug描述**
4.0.8版本可以正常自动关联弹幕，到了4.0.9版本无法加载弹幕

**设备信息（请回答下列问题）：**
 - 设备：索尼 9000H
 - OS：Android 10.0
 - 程序版本：4.0.9正式版

**Comment by jiayiming** [comment]
同样问题  现在只能按向下出菜单

**Comment by 494556411** [comment]
+1

**Comment by zyujs** [comment]
同样的问题
v4.1.0 Beta 依然无法自动加载

**Comment by rakaki** [comment]
同样的问题，只能手动加载

**Comment by xyoye** [comment]
请更新至4.1.0再试试
