### ISSUE TITLE
使用cloudreve挂载onedrive后开启webdav可以正常连接，但是视频无法正常播放

### ISSUE THREAD

**Issue by weiyongzenqi** [xyoye/DanDanPlayForAndroid#186]
**Bug描述**
使用cloudreve挂载onedrive后开启webdav可以正常连接，但是视频无法正常播放
![Screenshot_2023-06-24-21-14-54-123_com xyoye dandanplay](https://github.com/xyoye/DanDanPlayForAndroid/assets/67868002/7e5c93ba-72be-4418-91e3-816c82bcc800)
切换其他内核也无法正常播放

**如何重现**
重现该程序行为的步骤：
1. 搭建cloudreve项目
2. 使用cloudreve挂载onedrive
3. 在cloudreve中开启webdav连接
4. 使用弹弹play连接cloudreve开启的webdav后，无法正常播放（cloudreve开启的webdav会将将onedrive的链接提交给请求方进行下载，onedrive的链接请求后并不带有mp4等媒体格式后缀，推测在这里播放失败）

**希望的正确行为**
正常通过弹弹play播放出视频
**屏幕截图**
如果适用的话，请添加一些屏幕截图以帮助解释您的问题。使用sm.ms图床服务会是一个好主意。

**设备信息（请回答下列问题）：**
 - 设备：红米k40
 - OS：miui14（Android13）
 - 程序版本：4.0.9

**附加内容**
如果需要测试我可提供已经建好的cloudreve提供的webdav

**Comment by xyoye** [comment]
我这边需要相关账号进行测试，麻烦请加下我QQ：155452509

**Comment by Freddd13** [comment]
@weiyongzenqi 我也遇到了这个问题，请问你解决了吗？ 
之前就是播放不了，但上周不知道为什么从OneDrive app点开视频，选其他应用打开就能看了，现在又不行了。

**Comment by weiyongzenqi** [comment]
> @weiyongzenqi 我也遇到了这个问题，请问你解决了吗？ 之前就是播放不了，但上周不知道为什么从OneDrive app点开视频，选其他应用打开就能看了，现在又不行了。

不好意思今天才看到 这个问题已经解决了,在最新的4.10测试版 下载测试版的安装包就可以了

**Comment by Freddd13** [comment]
感谢回复。我下了4.1.0，确实可以播放了，只是感觉播放很卡，而且卡的时候会有很多马赛克出现，在相同网络环境下通过dav播放视频，我安卓的nplayer和windows 的potplayer均无此卡顿现象，请问你有遇到这个问题吗…
