### ISSUE TITLE
关于sd卡支持

### ISSUE THREAD

**Issue by ktugya** [xyoye/DanDanPlayForAndroid#187]
**您的功能请求是否与一个问题有关？请说明。**
本地媒体库似乎不能选择SD卡，是否可以加入SD卡支持？

**描述你所想要的解决方案**
高版本的Android似乎有对SD卡的访问限制，但我发现via浏览器，es等应用似乎可以通过系统文件管理器授权来访问SD卡。

**Comment by xyoye** [comment]
可以通过新增“设备存储库”实现SD卡访问
