### ISSUE TITLE
无法正确识别命名模板

### ISSUE THREAD

**Issue by koolcandy** [xyoye/DanDanPlayForAndroid#191]
**Bug描述**
我的番剧命名格式为“白圣女与黑牧师 S01E01.mp4”，在此命名规则下，无法自动匹配弹幕，手动匹配直接粘贴，该命名也无法匹配

**如何重现**
重现该程序行为的步骤：
使用webdav访问服务器，打开视频无法正确匹配，手动匹配时直接点击文件名，例如“白圣女与黑牧师 S01E01.mp4”，同样无法匹配，似乎不能识别 S01E01
**希望的正确行为**
正确匹配弹幕

**屏幕截图**
如果适用的话，请添加一些屏幕截图以帮助解释您的问题。使用sm.ms图床服务会是一个好主意。

**设备信息（请回答下列问题）：**
 - 设备：红米k40
版本：4.0.10， 4.0.9
**附加内容**
在这里加上其他所有有关该Bug的内容。

**Comment by koolcandy** [comment]
又多测试了几次，在本地播放这个命名方式可以正常识别，使用其他软件串流播放也可以自动识别，也就自带的webdav中播放，无法正常识别

**Comment by xyoye** [comment]
此问题已修复，请更新至4.1.0再试试
