### ISSUE TITLE
4.0.9播放页面在电视机上的默认遥控确认按键在返回上

### ISSUE THREAD

**Issue by KazeLiu** [xyoye/DanDanPlayForAndroid#192]
我是用emby调用弹弹PLAY播放视频。

因为播放页面默认的按钮是返回，就导致有时候想暂停，直接按遥控中键导致触发返回。

然而客户端和emby服务器链接的关系，导致播放器无法断点续播，emby那边再播放又要从头开始放，然后应为转码的速度问题又只能10秒步进，就很阴间。

我依稀记得以前的版本是能断点续传也是默认的遥控中键播放暂停，不知道这个版本是因为什么原因消失了

我希望您的播放器在电视端进入播放页面时能默认的播放暂停按钮，而不是返回。

如果有可能的话，能联动emby的库能同步播放时长那就更好了

**Comment by xyoye** [comment]
暂停问题已修复，请更新至4.1.0版本

emby进度同步问题暂不考虑
