### ISSUE TITLE
设备存储库模式下不能自动装载弹幕

### ISSUE THREAD

**Issue by Penixv** [xyoye/DanDanPlayForAndroid#194]
**Bug描述**
在使用“设备存储库”加载usb设备（U盘，移动硬盘）上的视频时，弹幕无法自动装载，需要手动从网络弹幕检索

**如何重现**
重现该程序行为的步骤：
同bug描述

**希望的正确行为**
能够自动装载存储在usb设备的视频的弹幕

**屏幕截图**

**设备信息（请回答下列问题）：**
 - 设备：红米K60
 - OS：Android 13.0（MIUI 14.0.25）
 - 程序版本：4.0.8 4.0.9 4.1.0（用过的）

**附加内容**

**Comment by xyoye** [comment]
已修复，请更新正式发布的4.1.0
