### ISSUE TITLE
4.0.9版本后手动选择第三方弹幕源失败

### ISSUE THREAD

**Issue by melulu578** [xyoye/DanDanPlayForAndroid#196]
4.0.9版本后弹幕源设置手动选没有了
只能通过弹幕右边三个点选择
但实际使用不管怎么选都只会下载dandanplay的弹幕，不会下载其他弹幕 
直接选会默认下所有弹幕合集
看识别有问题的番剧时无法过滤错误弹幕
比如间谍教室第二季6话会把5话弹幕也识别进去无法筛选
4.08版设置第三方手动后可以正常使用

**设备信息（请回答下列问题）：**
 - 设备：红米K60
 - OS：Android 13.0（MIUI 14.0.26）
 - 程序版本：4.0.9 4.1.0

**Comment by xyoye** [comment]
此功能已与4.1.0进行调整，请更新至4.1.0再试试
