### ISSUE TITLE
希望增加调节弹幕透明度显示的功能

### ISSUE THREAD

**Issue by wuge960812** [xyoye/DanDanPlayForAndroid#20]
**您的功能请求是否与一个问题有关？请说明。**
对问题简明扼要的描述。例如：在使用[...]时，我总觉得不大舒服。

**描述你所想要的解决方案**
简明扼要地描述您想要发生的事情。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要的描述。

**附加内容**
在这里加上其他所有有关该功能请求的内容。

**Comment by wuge960812** [comment]
。。。

**Comment by xyoye** [comment]
fixed
