### ISSUE TITLE
为啥没有下载功能

### ISSUE THREAD

**Issue by 280867678** [xyoye/DanDanPlayForAndroid#209]
**您的功能请求是否与一个问题有关？请说明。**
为什么下载功能还没有呢

**描述你所想要的解决方案**
希望完善磁力下载功能，应为磁力播放速度太慢了，播放很卡，希望在线完成播放或者边下边播放

**描述您考虑过的替代方案**

**附加内容**

**Comment by xyoye** [comment]
弹弹APP已经不考虑提供下载功能了，如果需要下载请复制链接到其它应用下载，专业的事情让专业的人做。
