### ISSUE TITLE
在其他文件管理器处添加启动入口

### ISSUE THREAD

**Issue by CJN96** [xyoye/DanDanPlayForAndroid#21]
您的功能请求是否与一个问题有关？请说明。
在用其他的文件管理器打开视频文件时，找不到用弹弹播放器打开的选项。

描述你所想要的解决方案：
希望能添加一个功能，在用其他的文件管理器打开视频文件时，能选择使用弹弹播放器打开。

**Comment by xyoye** [comment]
fixed
