### ISSUE TITLE
Bug 报告

### ISSUE THREAD

**Issue by zxc173123** [xyoye/DanDanPlayForAndroid#211]
**Bug描述**
删除了视频文件夹刷新过后显示还在只有重启手机或者卸载重装才能正确识别，清缓存没用

**如何重现**
重现该程序行为的步骤：
1. 打开小米文件管理器
2. 删除看完的动漫文件夹
3. 打开弹弹刷新
4. 删除的视频文件夹还显示

**希望的正确行为**
修复一下刷新问题

**屏幕截图**
这也没啥好截图的

**设备信息（请回答下列问题）：**
 - 设备：小米13
 - OS：安卓13
 - 程序版本：最新版

**附加内容**
还有弹幕不会自动加要自己手动搜索添加并且部分动漫搜不到弹幕但是b站港澳台是有这动漫的

**Comment by xyoye** [comment]
视频刷新问题，这个是系统MediaStore的机制导致的，APP是通过系统MediaStore来获取当前设备的视频文件，如果删除后系统媒体库未更新，则仍会显示视频。
当前的解决方式，可以在系统文件管理器视频类别中进行刷新。或者在APP扫描目录管理中加入常用的文件夹，这样在APP刷新时会对添加的文件夹进行遍历，此操作建议在最新4.1.0中进行。

后面应该也会在APP内增加通知系统刷新媒体库的功能。

弹幕问题，请提供具体视频信息，并在[弹弹社区](https://support.qq.com/products/104929)反馈
