### ISSUE TITLE
是否可以将远程访问整合进app

### ISSUE THREAD

**Issue by swhoro** [xyoye/DanDanPlayForAndroid#22]
**您的功能请求是否与一个问题有关？请说明。**
用浏览器进行远程访问感觉不太好操作播放界面；如果换一个网络环境，ip地址还有可能发生变化。
另外手机上下番剧总是没有电脑上方便

**描述你所想要的解决方案**
将远程访问整合进app，只要手机与电脑处于同一局域网，手机app即可访问电脑上的媒体库

**Comment by xyoye** [comment]
已在3.4.1添加远程访问

**Comment by swhoro** [comment]
谢谢，但是想问一下如果观看mkv格式封装的字幕的话有办法吗

**Comment by xyoye** [comment]
> 谢谢，但是想问一下如果观看mkv格式封装的字幕的话有办法吗

播放器设置中切换播放器内核为ExoPlayer可观看MKV字幕
