### ISSUE TITLE
bug无法播放

### ISSUE THREAD

**Issue by fx202438** [xyoye/DanDanPlayForAndroid#231]
提示无法播放
一些网站视频无法播放，去年看过同样的视频，可以播放，现在不行。试了另一个网站的视频，可以播放。
切换过其他播放器，全部都不行。
平时使用的是VLC。

无法播放的视频https://v.ddys.pro/v/Anime/SPY_FAMILY/SPY_FAMILY_S01E01.mp4
可以播放的视频
https://vip.ffzy-online1.com/20230101/19862_a5b64574/2000k/hls/mixed.m3u8

手机红米K30
手机版本：12.0.7
安卓版本10
软件版本：4.1.0
![Screenshot_2024-03-05-11-31-06-576_com xyoye dandanplay](https://github.com/xyoye/DanDanPlayForAndroid/assets/162689264/b6c67797-74f0-4624-b13d-72e1a9560857)

**Comment by xyoye** [comment]
![20240518220219](https://github.com/xyoye/DanDanPlayForAndroid/assets/23527777/d7e78f11-1154-46ca-8bb7-eb1a4376d250)


视频源问题，非APP异常
