### ISSUE TITLE
设置了基本路径的Alist无法加载目录

### ISSUE THREAD

**Issue by Yprolic** [xyoye/DanDanPlayForAndroid#235]
**Bug描述**
添加Alist存储库时，账号基本路径设置为根目录的可以工作，但配置设置了子路径的账号时，端上无法加载目录
服务端没有抓到相关access log

**如何重现**
1. alist侧新建账号，配置类似下图，基本路径设置为任意一个子路径
2. ![image](https://github.com/xyoye/DanDanPlayForAndroid/assets/7588470/95fdf99f-cea8-4f1e-8f11-b86eabcbf043)
3. 安卓概念版新增alist存储库，配置如下
![qq_pic_merged_1711184130842](https://github.com/xyoye/DanDanPlayForAndroid/assets/7588470/de3897c7-aecc-4777-a12b-d8c4bdfe6fa7)
4. 可以发现无法刷出目录页
5. ![image](https://github.com/xyoye/DanDanPlayForAndroid/assets/7588470/51c38d21-6f91-4e82-bdb0-f6cc2b27da95)

**设备信息（请回答下列问题）：**
 - 设备：iQOO Neo8 Pro
 - OS：Android13
 - 程序版本：4.1.0

**Comment by shinesky** [comment]
我也想知道，正确的挂载alist库的方式
