### ISSUE TITLE
注册账号时对输入进行验证

### ISSUE THREAD

**Issue by kaedei** [xyoye/DanDanPlayForAndroid#24]
注册账号时目前没有相关的输入验证和提示（例如账号密码允许多少位之类）。只有注册失败后服务器端返回的错误信息。
相关验证条件在api文档中可以看到 https://api.acplay.net/swagger/ui/index#!/Auth/Auth_RegisterMainUser

- 用户名。只能包含英文或数字，长度为5-20位，首位不能为数字。
- 密码。长度为5到20位之间。
- 备用邮箱（找回密码用）。长度不能超过50个字符。
- 昵称。长度不能超过50个字符，可以使用中文。

**Comment by xyoye** [comment]
已添加在3.2.2版本
