### ISSUE TITLE
有办法能不加载来自某个网站的弹幕吗

### ISSUE THREAD

**Issue by weirdo4253** [xyoye/DanDanPlayForAndroid#27]
辉夜大小姐第三话好像巴哈那边删减了，导致出现错位的问题，但是加载的弹幕是B站和巴哈混合的也没办法调轴

**Comment by kaedei** [comment]
> 辉夜大小姐第三话好像巴哈那边删减了，导致出现错位的问题，但是加载的弹幕是B站和巴哈混合的也没办法调轴

手机版获取到的弹幕都是已经合并后的，没办法单独调整某个来源。你可以点击首页公告“弹幕问题反馈入口”去反馈这个问题

**Comment by sunny12005** [comment]
想问下怎么可以自动加载弹幕？为什么我总是要手动选择？

**Comment by xyoye** [comment]
请更新4.0.0版本
