### ISSUE TITLE
分屏播放处于后台时自动暂停, 无法一遍刷游戏一边看

### ISSUE THREAD

**Issue by tsaisheng** [xyoye/DanDanPlayForAndroid#31]
**Bug描述**
安卓分屏后, 操作非播放器的那一半时, 播放器会自动暂停, 无法一边刷游戏一边看. 

**如何重现**
重现该程序行为的步骤：
1. 分屏, 在一半屏幕上打开弹弹play并播放视频
2. 点击另一半屏, 这时候弹弹play就自动暂停了

**希望的正确行为**
希望能一边玩一边看剧. 

**设备信息（请回答下列问题）：**
 - 设备：华为P9
 - OS：Android 8.0(emui8.0)
 - 程序版本：3.3.0

**附加内容**
弹弹play已经是我手机上的主力播放器了, 祝弹弹越来越好. お願いします.

**Comment by xyoye** [comment]
分屏后点击另一半屏的确会自动暂停，只需要再点击一次播放，视频会继续播放，并且操作其它应用时不会影响播放
