### ISSUE TITLE
长期使用后占用了巨量UPnP端口

### ISSUE THREAD

**Issue by nyfair** [xyoye/DanDanPlayForAndroid#34]
**如何重现**
在wifi网络环境中下载任意视频，都会通过依赖的libtorrent向路由器发出请求开启随机的tcp/udp端口，久而久之就会出线一长串UPnP端口列表，同时也造成潜在的安全隐患

**希望的正确行为**
建议提供设置选项可以固定端口或者退出时自动清空所映射的UPnP端口

**Comment by xyoye** [comment]
请更新4.0.0版本
