### ISSUE TITLE
放宽字幕文件名匹配

### ISSUE THREAD

**Issue by gin3715** [xyoye/DanDanPlayForAndroid#35]
希望能放宽对自动加载的字幕文件名的匹配规则，如对文件AAA.mp4，除了AAA.ass外，开头为AAA的字幕文件，如AAA.XX.ass也能匹配。

例子：
视频文件名：
[Nekomoe kissaten&Airota&LoliHouse] Yuru Camp - 01 [WebRip 1920x1080 HEVC-yuv420p10 AAC].mkv

需要自动加载的字幕文件名：
[Nekomoe kissaten&Airota&LoliHouse] Yuru Camp - 01 [WebRip 1920x1080 HEVC-yuv420p10 AAC].SC.ass
[Nekomoe kissaten&Airota&LoliHouse] Yuru Camp - 01 [WebRip 1920x1080 HEVC-yuv420p10 AAC].TC.ass

**Comment by xyoye** [comment]
通过规则匹配容易出现混乱，没有找到合适的方法。
