### ISSUE TITLE
亮度控制问题

### ISSUE THREAD

**Issue by qazesz1** [xyoye/DanDanPlayForAndroid#39]
**Bug描述**
在亮度极低的环境，手机打开自动亮度调节比关闭自动亮度调节时的亮度更低。弹弹play播放时默认接管亮度，禁用了自动亮度调节，使亮度变高

**如何重现**

**希望的正确行为**
默认不调整亮度

**屏幕截图**

**设备信息（请回答下列问题）：**
 - 设备：Pixel 1
 - OS：Android 8.1
 - 程序版本：3.3.2

**附加内容**

**Comment by xyoye** [comment]
请更新4.0.0版本
