### ISSUE TITLE
我很乐意为您的项目做出贡献。 (I'd love to contribute to your project). 

### ISSUE THREAD

**Issue by HarryHeights** [xyoye/DanDanPlayForAndroid#42]
你好，我是哈利。我参与为开源项目创建文档。这是我在帮助开源项目方面所做贡献的一部分。我参与创建的文档之一是隐私政策。隐私政策将提供有关用户信息收集，使用和安全性的详细信息。我真的不知道你是否从外部收集用户信息，但是，如果你不这样做，最好通过隐私政策让最终用户知道。
贡献者指南也是一份重要文件，可以帮助潜在的合作者轻松地为您的项目做出贡献。

我很想听听你对此的看法。

Hello, I'm Harry. I engage in creating documents for open source projects. It's part of my contribution in helping open source projects. One of the documents I engage in creating is a privacy policy. The privacy policy will give details about user information collection, use and security. I really don't know if you externally collect user information, but, if you don't, it's good to let end users know via a privacy policy.
Contributor's guidelines is also an important document that will help prospective collaborators contribute easily to your project.

I'll love to hear your thoughts on this.

**Comment by xyoye** [comment]
Hey Harry.

Thanks for reaching out. 

I hope this project is getting better, so I also think that the privacy policy is necessary, then what do I need to provide for you?

**Comment by HarryHeights** [comment]
I'll need a list of third-party libraries the app uses. 
Then do you collect any kind of user information/data when someone uses the app?
Do you collect crash logs?

I can get the rest information myself. Only those three above are what I need to know.

**Comment by xyoye** [comment]
1.I uploaded a full third-party list of files. [THIRD_PARTY_LIBRARIES](https://github.com/xyoye/DanDanPlayForAndroid/blob/master/THIRD_PARTY_LIBRARIES.md)
2.Get all the videos in the user’s phone，User registration requires a mailbox，Get phone model and Android version when user feedback
3.Yes, use bugly to collect crash logs

**Comment by HarryHeights** [comment]
Alright. Thanks for the information. I'll send a PR soon.

**Comment by xyoye** [comment]
I merged those pull requests, thank you for your contribution!

**Comment by HarryHeights** [comment]
Alright thanks. If there's anything related to content creation you'd like me to, I'm available
