### ISSUE TITLE
播放视频时画面一卡一卡的。

### ISSUE THREAD

**Issue by xxxloli123** [xyoye/DanDanPlayForAndroid#45]
**Bug描述**
对Bug的简明扼要的描述。

**如何重现**
重现该程序行为的步骤：

1. 下载 裤袜视界 3
2. 下载 
【MMSUB x U3-Web】★完整版★[丝袜视界 / 丝袜视界 / Miru Tights / みるタイツ][03][WebRip 1080p HEVC-10bit AAC OPUS][简繁日英内封字幕] (裤袜视界 , 裤袜视界)

3。下载成功后播放  画面就一卡一卡的

**希望的正确行为**
希望可以尽快修复一下。
对你所希望程序应作出的正确行为（即没有bug时的行为）的简明扼要的描述。

**屏幕截图**
如果适用的话，请添加一些屏幕截图以帮助解释您的问题。使用sm.ms图床服务会是一个好主意。

**设备信息（请回答下列问题）：**
Android 版本
8.0.0
手机型号
MI 6

弹弹play-概念版-3.3.3-17-203511.apk
27.92 MB
5月 29, 09:03

**附加内容**
在这里加上其他所有有关该Bug的内容。

**Comment by xyoye** [comment]
媒体库页面 ->任一文件夹-> 右上角播放器设置 -> 尝试切换播放器为ijkplayer

**Comment by lkdong-cn** [comment]
播放视频时画面一卡一卡问题，我觉得是：

设备cpu性能不是很强，因为目前播放视频解码可能用的是软解码，cpu性能不够强会导致解码速度跟不上播放速度，若播放时候没有加上播放缓存处理，绝对有可能导致播放一卡一卡的。

解决方法：加上缓存播放处理，如果播放出现卡吨时候，就暂自动停播放，缓存5s或者10s后，再自动播放。

**Comment by lkdong-cn** [comment]
> 媒体库页面 ->任一文件夹-> 右上角播放器设置 -> 尝试切换播放器为ijkplayer

源码我只是大概看了一下，期望优化几个功能：
1、是否支持smb在线播放，smb://xxx ，比如像http一样，可以直接播放。这个是可以实现的。

2、加上播放缓存处理，不管是本地播放，还是播放流媒体。

3、加上一个可以控制字幕大小、字幕字体颜色、字幕显示位置等等。这个很简单，直接操作显示字幕textview即可实现。

4、要注意ijkplayer播放4k视频时，切换字幕或音轨可能会引发一些问题，具体有哪些问题，我已经有2～3年没有看ijkplayer开源框架了，有些问题我也记不起来了，不过你要小心。

5、我觉得可以加强用户体验，可以加上一个自动切换播放器功能，比如默认播放用ijkplayer，如果ijkplayer不支持播放，自动切换到其他播放器，如果还是不支持播放，继续切换到另一个播放器播放。如果在不支持时候，没必要让用户去选择播放器播放。特别支持播放器多了，用户不好选择。
