### ISSUE TITLE
弹幕格式可以从xml 转为ass吗

### ISSUE THREAD

**Issue by xxxloli123** [xyoye/DanDanPlayForAndroid#46]
**您的功能请求是否与一个问题有关？请说明。**
对问题简明扼要的描述。例如：在使用[...]时，我总觉得不大舒服。

**描述你所想要的解决方案**
简明扼要地描述您想要发生的事情。
弹幕格式可以从xml 转为ass吗

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要的描述。

**附加内容**
在这里加上其他所有有关该功能请求的内容。

**Comment by xyoye** [comment]
弹弹play不提供这个功能
