### ISSUE TITLE
发送弹幕 或者选择字幕后 不能隐藏 虚拟按键。

### ISSUE THREAD

**Issue by xxxloli123** [xyoye/DanDanPlayForAndroid#47]
**Bug描述**
对Bug的简明扼要的描述。

**如何重现**
重现该程序行为的步骤：
1. 到达 '...' 位置
2. 点击 '....'
3. 滚动至 '....'
4. 错误出现

**希望的正确行为**
对你所希望程序应作出的正确行为（即没有bug时的行为）的简明扼要的描述。
希望能尽快修复。

**屏幕截图**
如果适用的话，请添加一些屏幕截图以帮助解释您的问题。使用sm.ms图床服务会是一个好主意。

**设备信息（请回答下列问题）：**
Android 版本
8.0.0
手机型号
MI 6弹弹play-概念版-3.3.3-17-203511.apk
27.92 MB
5月 29, 09:03
 - 设备：[比如 Pixel 2]
 - OS：[比如 Android 8.0(Google)]
 - 程序版本：[比如 3.0.0]

**附加内容**
在这里加上其他所有有关该Bug的内容。

**Comment by xyoye** [comment]
已在3.4.1修复
