### ISSUE TITLE
始终会全盘扫描

### ISSUE THREAD

**Issue by binbin000** [xyoye/DanDanPlayForAndroid#49]
媒体库扫描时默认扫描整个磁盘，添加了单独的扫描文件夹依然会全盘扫描，虽然有屏蔽功能，但是需要屏蔽的其他文件夹太多。

例如，我只想要扫描某一个文件夹，现在的操作就是要屏蔽出这个文件夹以外得其他文件夹，很麻烦，也不易操作。

建议默认只扫描常用的媒体文件夹，同时提供单独添加和屏蔽的功能。

可以像vlc那样让用户选择媒体库能够扫描那些文件夹

**Comment by xyoye** [comment]
文件扫描将会在后续版本优化
