### ISSUE TITLE
请问下载种子的模块可否单独使用，可否支持链接下载

### ISSUE THREAD

**Issue by hiliving** [xyoye/DanDanPlayForAndroid#51]
这个项目的下载功能很实用，能否提供一个封装库呢，另外，可否支持磁力链接下载，以及普通链接下载？类似迅雷的功能

**Comment by xyoye** [comment]
弹弹play概念版不开放自定义链接下载，如有需要可自己从项目中抽离下载模块，而且下载模块都是引用的第三方库，只是根据项目需要做了修改。

**Comment by xyoye** [comment]
另外如果你想抽离下载模块，提供一些介绍。当前项目共有三个分支分别对应三个下载库：

master分支使用[libtorrent](https://gitlab.com/axet/libtorrent)，普通下载可以，内部存在一些bug，已经准备放弃。
frostwire分支使用[jlibtorrent](https://github.com/frostwire/frostwire-jlibtorrent)，功能较为完善，准备适配使用。
thunder分支使用的是迅雷的下载库，支持边下边播，目前据我了解个人开发的能边下边播的App应该都是使用这个库，但是曾经出现过一段时间不能使用。

我仅仅是对这些第三库在下载任务管理方面做了适配及修改，如果有开发需要建议下载源库。

**Comment by hiliving** [comment]
thunder这个库我知道，有些资源被迅雷和谐不能下载，我试试jlibtorrent
