### ISSUE TITLE
可不可以把关注状态和关注功能本身整合为一个按钮

### ISSUE THREAD

**Issue by sceic** [xyoye/DanDanPlayForAndroid#52]
目前我要关注按钮在右上角，且为白色文字，偶尔会被一些白色的动画海报配色完全吃掉而看不到。而关注状态又在下面好几行的地方，关联度不高。

希望考虑直接把关注状态按钮设置为可点击，然后切换关注中，与未关注状态。 删除现有右上角独立关注按钮。

**Comment by xyoye** [comment]
已在3.4.1版本修改
