### ISSUE TITLE
这个网络川牛播放，不能手动加载弹幕。

### ISSUE THREAD

**Issue by xxxloli123** [xyoye/DanDanPlayForAndroid#54]
**Describe the bug**
老哥，这个网络川牛播放，不能手动加载弹幕。
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.Use Image Hosting Services like sm.ms is a good idea.

**Device (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android 8.0(Google)]

**Additional context**

**Comment by xyoye** [comment]
请更新4.0.0版本
