### ISSUE TITLE
希望能加一个弹幕正则匹配的功能

### ISSUE THREAD

**Issue by PlayerYao** [xyoye/DanDanPlayForAndroid#57]
使用dandan play播放视频时，有时会加载到不想看的弹幕，例如港澳台的弹幕(梗文化不互通)，无聊的抢楼刷时间之类的弹幕。
关键词屏蔽对于这种弹幕来说根本起不到多少作用。
希望可以在播放器读取弹幕时可以匹配正则过滤掉不想要的弹幕

**Comment by xyoye** [comment]
请更新4.0.0版本
