### ISSUE TITLE
建议新增android电视遥控操作

### ISSUE THREAD

**Issue by reaink** [xyoye/DanDanPlayForAndroid#59]
**您的功能请求是否与一个问题有关？请说明。**
新建对android电视上的遥控操作支持

**Comment by xyoye** [comment]
tv版在路上

**Comment by lsl330** [comment]
希望能支持tv+1，制作组加油

**Comment by bssxmh** [comment]
同求TV版，辛苦了

**Comment by zyyf** [comment]
现在tv上装了安卓版，但是播放的时候不显示选项，导致没法调节弹幕大小。。

**Comment by SettingDust** [comment]
希望适配一下操作，在视频播放页面点击上/下可以打开控制栏，
- [ ] 但是没办法关闭/打开弹幕，好像没索引，怎么操作都过不去
- [ ] 字幕、弹幕的设置可以打开，但是好像一样没索引，过不去
- [ ] 文件列表点进一个文件夹之后，当前选项还在之前的列表里，需要一直摁着下，看运气到当前文件夹（需要看当前文件列表有多少文件、前一个文件列表有多少文件），进新的文件夹清除一下 focus 状态吧 orz，很折磨
