### ISSUE TITLE
安卓版, 播放中鎖屏, 解鎖後從頭播放,没有承接進度播放

### ISSUE THREAD

**Issue by nganhkcn** [xyoye/DanDanPlayForAndroid#64]
**Describe the bug**
安卓版, 播放中鎖屏, 解鎖後從頭播放, 没有承接進度播放

**To Reproduce**
See topic

**Expected behavior**
承接進度播放

**Screenshots**
N/A

**Device (please complete the following information):**
 - Device: mix2s & POCO F2
 - OS: MIUI 11
 - Version 3.5.3

**Additional context**
Nil

**Comment by StarVerseZ** [comment]
在android 11 的一加8上也复现了此问题。表现为锁屏或解锁都会从开始播放。版本号3.5.5。可以提供详细日志

**Comment by xyoye** [comment]
请更新4.0.0版本

**Comment by StarVerseZ** [comment]
问题不再出现了。感谢开发者，thanks！
