### ISSUE TITLE
弹幕的设置不能继承到下一个视频 打开新视频会自动重置

### ISSUE THREAD

**Issue by snowoneyebrow** [xyoye/DanDanPlayForAndroid#68]
**Bug描述**
弹幕的设置不能继承到下一个视频 打开新视频会自动重置 具体的弹幕选项为弹幕同屏数量和弹幕屏蔽

**设备信息（请回答下列问题）：**
 - 设备：小米mix2
 - OS：miui12
 - 程序版本：3.5.5

**Comment by xyoye** [comment]
请更新4.0.0版本
