### ISSUE TITLE
概念版远程访问交互方式修改建议

### ISSUE THREAD

**Issue by sunjx17** [xyoye/DanDanPlayForAndroid#69]
因为在PC端存了数千集（应该超过100部番剧了吧）用概念版远程访问时只显示一个缩略图+文件名列表，无法快速定位到想看的那一集。

**描述你所想要的解决方案**
远程访问连接后的一口气划到底的文件列表改成：番剧列表->缩略图+文件名/分集标题（类似网页版远程访问），并在顶部添加搜索栏。

**描述您考虑过的替代方案**
只用网页版看番，然而mkv格式/MP4(hevc)格式浏览器是放不了的。

**附加内容**
（看远程访问API列表里面貌似只能一下子获取库中的所有内容……json大约有2.94MB，而客户端的缩略图是懒加载，如果能加一个缓存以免重复访问就更好了，当然也可以手动刷新缩略图或列表这样的……）

**Comment by CberYellowstone** [comment]
客户端是否缓存缩略图是由服务端的header决定的,DanDanPlay电脑版给出的默认请求头应该是no-cache

**Comment by CberYellowstone** [comment]
@xyoye 能不能将此问题尽快提上日程?
