### ISSUE TITLE
本地弹幕的文件夹不能改了

### ISSUE THREAD

**Issue by hiyominato** [xyoye/DanDanPlayForAndroid#77]
建议加上 修改默认弹幕存放位置 的功能。
自己的弹幕xml文件，因为安卓11的限制，无法移动到默认的data文件夹。
想自己加弹幕还要往外翻好几层文件夹。
旧版本可以放在 Android/media/包名/ 里，也不需要存储权限🥲

多谢开发者一直的努力啦🥳🥳

**Comment by xyoye** [comment]
好的，这个会考虑一下如何处理

**Comment by Sanlorng** [comment]
@xyoye 参考Solid Explorer的实现，可以用SAF获取某个文件夹的访问权限
