### ISSUE TITLE
4.0.0问题反馈：播放卡顿

### ISSUE THREAD

**Issue by Gokou-Ruri** [xyoye/DanDanPlayForAndroid#78]
**Bug描述**
对Bug的简明扼要的描述。

**如何重现**

1. 在ijk内核下打开某个视频后（无论软硬解码均如此），画面帧率目视只有1fps左右（即卡顿），且没有声音，大约持续2-3秒左右，恢复正常。而在exo内核下打开某个视频后，画面黑屏，持续也是2-3秒左右恢复正常。3.x版本无此问题。
2. 补充1：h.264/h.265编码的番剧视频均会出现这个情况，哪怕是非常短的低画质小视频也会这样。
3. 补充2：关闭OpenSL ES后卡顿会有改善，但问题依旧存在。没办法像MX等普通播放器那样打开视频后立刻流畅播放视频。

**希望的正确行为**
对你所希望程序应作出的正确行为（即没有bug时的行为）的简明扼要的描述。

**屏幕截图**
如果适用的话，请添加一些屏幕截图以帮助解释您的问题。使用sm.ms图床服务会是一个好主意。

**设备信息（请回答下列问题）：**
 - 设备：[红米 k20 pro]
 - OS：[Android 11 ]
 - 程序版本：[4.0.0]

**附加内容**
在这里加上其他所有有关该Bug的内容。

**Comment by wzhen0315** [comment]
我在平板开发板上也遇到了类似的问题（程序版本是4.0.4），视频播放两分钟后出现卡顿和丢帧，过一段时间（15秒）后回复正常，切换回3.x版本后没有问题了。两个版本比对发现默认播放设置不同，暂时还没验证是不是这个问题
