### ISSUE TITLE
功能请求：支持完整的外挂字幕样式

### ISSUE THREAD

**Issue by Revincx** [xyoye/DanDanPlayForAndroid#83]
**您的功能请求是否与一个问题有关？请说明。**
大概算是，有些内容比较丰富的字幕在移动端的显示效果非常不好，会在下面堆成一块。

**描述你所想要的解决方案**
希望对外挂字幕引擎进行优化，能够支持外挂字幕的位置，颜色，字体等样式。

**描述您考虑过的替代方案**
如果不能完整支持的话，只做到位置能正确显示也可以的

**附加内容**
不是很了解目前所使用的外挂字幕系统，请问这个请求难实现吗？

**Comment by xyoye** [comment]
未来可能会通过接入VLC来解决这个问题， 除了VLC外，暂时没找到有其它方案可做到完整支持字幕样式。

**Comment by Revincx** [comment]
> 未来可能会通过接入VLC来解决这个问题， 除了VLC外，暂时没找到有其它方案可做到完整支持字幕样式。

期待能接入VLC，或者把VLC做成可选的播放引擎也可以

**Comment by YuukiHibiki** [comment]
> 未来可能会通过接入VLC来解决这个问题， 除了VLC外，暂时没找到有其它方案可做到完整支持字幕样式。

mxpalyer有调用本地字体文件夹从而来实现和potplayer一样的播放效果，这个功能容易效仿吗？
