### ISSUE TITLE
安卓版视频倍速后弹幕还是原来的速度

### ISSUE THREAD

**Issue by FANGFUJUN** [xyoye/DanDanPlayForAndroid#84]
**Bug描述**
对Bug的简明扼要的描述。
安卓版视频倍速后弹幕还是原来的速度
**如何重现**
重现该程序行为的步骤：
1. 到达 '视频设置' 位置
2. 点击 '视频倍速'
3. 滚动至 '视频倍速'
4. 错误出现视频是倍速，可弹幕还是原来的速度
安卓版视频倍速后弹幕还是原来的速度
**希望的正确行为**
对你所希望程序应作出的正确行为（即没有bug时的行为）的简明扼要的描述。
我希望弹幕能够和视频速度一样
**屏幕截图**
如果适用的话，请添加一些屏幕截图以帮助解释您的问题。使用sm.ms图床服务会是一个好主意。

**设备信息（请回答下列问题）：**
 - 设备：[华为8X MAX]
 - OS：[比如 Android 9.0]
 - 程序版本：[比如 4.0.1]

**附加内容**
在这里加上其他所有有关该Bug的内容。

**Comment by xyoye** [comment]
#73
