### ISSUE TITLE
因为文件名中的%20而在搜索弹幕时没有候选词

### ISSUE THREAD

**Issue by anjia1991** [xyoye/DanDanPlayForAndroid#86]
**Bug描述**
对Bug的简明扼要的描述。

**如何重现**
重现该程序行为的步骤：
1. 使用文件管理器打开nas上的文件
2. 播放器没有识别%20为空格，在关联弹幕时需要手动输入番剧名称。

**希望的正确行为**
转换%20为空格并正确提供番剧名称来搜索弹幕。

**屏幕截图**
![Screenshot_2021-04-06-19-12-36-544_crop.jpg](https://i.loli.net/2021/04/06/k7KpFUmn8rwuGyz.jpg)

**设备信息（请回答下列问题）：**
 - 设备：坚果R2
 - OS：Android 10
 - 程序版本：4.0.2

**Comment by MagmaBlock** [comment]
这个是[url编码](http://tool.chinaz.com/tools/urlencode.aspx)的问题  **似乎**除了本地和bt播放策略以外   其他方法播放的视频名全都是经过url编码过的...
中文文件名就更乱了。。不过经过url编码解码之后就是正常的名字了   等待修复（
话说目前即使是文件名正常，弹幕似乎也经常匹配不上x

**Comment by xyoye** [comment]
请查看最新版
