### ISSUE TITLE
[BUG] 远程媒体库 播放失败, 请尝试更改播放器设置, 或者切换其他播放内核

### ISSUE THREAD

**Issue by SINC-G** [xyoye/DanDanPlayForAndroid#88]
**Bug描述**
远程媒体库无法播放视频

**如何重现**
1. PC端开启远程访问, 设置API密钥与web验证
2. 安卓端添加远程媒体库, 测试通过
3. 播放视频失败...

**希望的正确行为**
正常播放视频

**屏幕截图**

![image](https://user-images.githubusercontent.com/47666274/114035204-7553ed80-98b1-11eb-87ba-d34ce6677fe0.png)

![image](https://user-images.githubusercontent.com/47666274/114035830-0e830400-98b2-11eb-9d08-eb4165ac6390.png)

**设备信息（请回答下列问题）：**
 - 设备：Redmi Note 8 Pro
 - OS：Android 10 | MIUI 12.0.5 稳定版
 - 程序版本：
     - PC端: Windows客户端(32位) 11.2.0.311
     - 安卓端: 4.0.2

**附加内容**
使用IJK Player与Exo Player都无法播放, 但EXO Player有些视频可以看到弹幕再弹出错误(但也有视频是只有黑屏)

尝试更改播放器设置, 无法解决

**Comment by MapleWithered** [comment]
可以尝试一下关闭PC端API密钥

**Comment by nKsnC** [comment]
> 可以尝试一下关闭PC端API密钥

@MapleWithered 感谢, 解决了

还是希望后续更新能解决这个问题

**Comment by xyoye** [comment]
请查看最新版
