### ISSUE TITLE
WebDav媒体库似乎不支持链接无后缀名的视频

### ISSUE THREAD

**Issue by MagmaBlock** [xyoye/DanDanPlayForAndroid#90]
**Bug描述**
WebDav媒体库似乎不支持 ~~链接无后缀名的视频~~ 
似乎不支持需要重定向一次的链接？
（如 [此链接](https://cloud.5t5.top/api/v3/file/source/2109/%5BNC-Raws%5D%20%E5%88%AE%E6%8E%89%E9%AC%8D%E5%AD%90%E7%9A%84%E6%88%91%E8%88%87%E6%92%BF%E5%88%B0%E7%9A%84%E5%A5%B3%E9%AB%98%E4%B8%AD%E7%94%9F%20-%2004%20%5BB-THM%5D%5BWEB-DL%5D%5B1080p%5D%5BAVC%20AAC%5D%5BCHS_CHT_SRT%5D%5BMKV%5D.mkv?sign=BHVAbp46uI96Whs-yuZMn3MXmJRb3Ox27-1aILtqvcw%3D%3A0)）

**如何重现**
重现该程序行为的步骤：

1. 我这边用Cloudreve搭建了一个基于OneDrive的网盘，想做媒体库。
2. 测试发现，OneDrive里面的视频只能被网盘程序获取到 ~~**不是**“.mp4 / .xxx”结尾的链接~~ **需要经过一次重定向的链接** ，而这种链接似乎无法被弹弹play的webdav功能识别，提示【播放失败，请尝试更改播放器设置，或者切换其他播放内核】

**希望的正确行为**
把相同的视频链接用串流功能来打开就能播放了，个人没有开发经验...怀疑是WebDav模式下缺少某些判断的逻辑
_如果需要出现上述问题的WebDav服务器来Debug的话可以联系我（_

**设备信息（请回答下列问题）：**
 - 设备：MI8SE
 - OS：Android 10  MIUI
 - 程序版本：还蛮新的4.0.2

**Comment by MagmaBlock** [comment]
![](https://files.catbox.moe/822pwx.png)

我用wget尝试下载了一下，这类链接应该是被302重定向了一次，才指向正确的视频地址
如果我没搞错的话，webdav应该也是用的http协议，那这个问题大概是因为webdav播放缺少了一个重定向判断的部分
（大概）

**Comment by xyoye** [comment]
我这边尝试将上述链接硬编码到APP中，并没有复现问题，所以怀疑是文件名导致的问题，4.0.3版本已经对此进行了优化，可以更新后再试试

**Comment by MagmaBlock** [comment]
我用4.0.3看了下，问题更严重了...对象存储的视频也放不出来了
我再解释下
我网盘程序这边是用Onedrive做的存储（也支持用对象存储来作为存储策略）
webdav功能是由网盘程序实现的
经过抓包  无论是网盘网页端  还是用webdav客户端链接，在访问文件的时候实际上都是在访问网盘背后的Onedrive（或者对象存储），流量不走服务器。
本来在旧版本里 用Onedrive

**Comment by MagmaBlock** [comment]
我用4.0.3看了下，问题更严重了...对象存储的视频也放不出来了...
我详细的解释下
### WebDAV 和网盘程序
我网盘程序（Cloudreve）这边是用 OneDrive 做的存储策略（也支持用对象存储来作为存储策略）
WebDAV 功能是由网盘程序模拟实现的。
经过抓包，无论是网盘网页端，还是用WebDAV客户端，在访问文件的时候实际上都是在访问网盘背后的OnedDive（或者对象存储），流量是不走网盘服务器的。

### OneDrive 和 对象存储
由于 OneDrive 限制，正常是不能得到 OneDrive 的永久文件直链的。所以说在用网盘程序访问存储在 OneDrive 里的文件时，需要先调用网盘程序的 API ，网盘程序再去获取 OneDrive 的临时下载链接，最后网盘程序给客户端回复 302 重定向，如同我第二条回复。

对象存储的文件对公网开放，不需要鉴权，因此有直链就能直接访问文件，不需要任何的重定向。

### 故障体现
#### 4.0.2

- 存在对象存储的视频
   - 串流播放 √
   - WebDAV 访问网盘后播放 √
- 存在 OneDrive 的视频
   - 串流播放 √
   - WebDAV 访问网盘后播放 ×

对于 OneDrive，网盘程序提供了一个 API 地址，访问那个地址，服务器就会返回对应视频的临时链接。这个地址在弹弹的串流播放里一切正常。但是使用媒体库功能访问网盘里的对应视频，就不能播放了。
**我怀疑**是 WebDAV 媒体库对此类视频链接缺少一个重定向的判断（？虽然不太确定，但是 WebDAV 应该也是 HTTP 协议的）

#### 4.0.3

- 存在对象存储的视频
   - 串流播放 √
   - WebDAV 访问网盘后播放 **×**
- 存在 OneDrive 的视频
   - 串流播放 √
   - WebDAV 访问网盘后播放 ×

更新之后，对象存储的视频也不能通过 WebDAV 播放了...不过串流播放仍然什么都能播就是麻烦

### 其他可能有用的东西
我出现问题的 WebDAV，可以测试一下
https://cloud.5t5.top/dav
bangumi@magma.ink
DqjYLfLLSIpaf8Cxmv8TCJa1xXPaOVmu
文件分布在哪个地方存储可以参考这个图
![](https://files.catbox.moe/pg85s3.jpg)

我发现，酷安上的[这个文件管理器](https://www.coolapk.com/apk/in.mfile)挂载 WebDAV 后再调用弹弹 Play 播放，就不会有任何 BUG。
不过好像不是开源的
打开视频文件时，弹弹 Play  似乎不属于视频播放器分类...?   #85

**Comment by xyoye** [comment]
你好，我这边经过测试已经找到问题发生的原因。首先有两个情况：1.使用IJK内核与EXO内核，2.使用VLC内核

1.IJK和EXO内核内部是默认自动进行重定向的，但是在重定向时会将原请求的headers复制到重定向请求的headers，因此重定向的请求时带有鉴权信息的，所以本该不需要鉴权的请求反而带有鉴权，导致验证失败，错误码是401。
2.VLC内核是通过APP内部的代理服务来处理网络请求，在重定向时会自动丢弃headers中鉴权信息，但是由于是代理服务，headers中会包含一个请求头：host，该请求头的存在也会导致请求失败，错误码是403。

目前有两种方案可以处理上述情况：
1.你更改服务器验证处理，主动丢弃客户端请求中authorization和host请求头，这样无论是哪种内核都可以播放视频，且不需要更新APP。
2.我这边更改一些代码后发给你一个特殊版本，该版本的VLC内核在重定向时会丢弃host请求头，让视频得以播放。但是IJK和EXO内核无法进行更改，因为重定向的操作是内核内部处理，这边无法改到。

**Comment by MagmaBlock** [comment]
> 你好，我这边经过测试已经找到问题发生的原因。首先有两个情况：1.使用IJK内核与EXO内核，2.使用VLC内核
> 
> 1.IJK和EXO内核内部是默认自动进行重定向的，但是在重定向时会将原请求的headers复制到重定向请求的headers，因此重定向的请求时带有鉴权信息的，所以本该不需要鉴权的请求反而带有鉴权，导致验证失败，错误码是401。
> 2.VLC内核是通过APP内部的代理服务来处理网络请求，在重定向时会自动丢弃headers中鉴权信息，但是由于是代理服务，headers中会包含一个请求头：host，该请求头的存在也会导致请求失败，错误码是403。
> 
> 目前有两种方案可以处理上述情况：
> 1.你更改服务器验证处理，主动丢弃客户端请求中authorization和host请求头，这样无论是哪种内核都可以播放视频，且不需要更新APP。
> 2.我这边更改一些代码后发给你一个特殊版本，该版本的VLC内核在重定向时会丢弃host请求头，让视频得以播放。但是IJK和EXO内核无法进行更改，因为重定向的操作是内核内部处理，这边无法改到。


感谢解答！
这么说主要还是cloudreve的问题
目前感觉他的webdav兼容性也不怎么好，在其他地方有时候也会出不少bug。。
我试试能不能改一下他这个软件或者用啥方法拦截一下http里多余的部分吧
再次感谢！

**Comment by xyoye** [comment]
> > 首先有两个情况：1.使用IJK内核与EXO内核，2.使用VLC内核
> > 1.IJK和EXO内核内部是自然自动产生的，但是在复制时带有原始请求的headers，从而产生的请求时鉴权信息的，所以本不需要鉴权的请求来源带有鉴权，导致错误是401 2.VLC核心是通过APP的代理服务来处理网络请求，在创业时会自动设计内部鉴权，但是由于是代理服务，标题中会包含一个请求头：主机，该请求头的存在也会导致请求失败，错误码是403。
> > 目前有两种处理情况： 1. 更改您的服务器验证处理，可以采取主动保护上述措施，中授权和主机请求头，这样无论是解决方案，知识都提供视频，而无需请求更新APP。 2. 我某些更改代码后该版本的 VLC 内核在某些时候会删除主机请求头，视频播放。IJK 和 EXO 内核无法进行更改，因为控制器的操作是内核内部处理，无法更改。
> 
> 作者，你好，我也出现了这个问题，是否可以发我一个特殊版本呢？

可以，留一下邮箱或加我QQ

**Comment by GodOfKiller** [comment]
***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xyoye/DanDanPlayForAndroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月10日(星期天) 下午2:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xyoye/DanDanPlayForAndroid] WebDav媒体库似乎不支持链接无后缀名的视频 (#90)





   
首先有两个情况：1.使用IJK内核与EXO内核，2.使用VLC内核
 1.IJK和EXO内核内部是自然自动产生的，但是在复制时带有原始请求的headers，从而产生的请求时鉴权信息的，所以本不需要鉴权的请求来源带有鉴权，导致错误是401 2.VLC核心是通过APP的代理服务来处理网络请求，在创业时会自动设计内部鉴权，但是由于是代理服务，标题中会包含一个请求头：主机，该请求头的存在也会导致请求失败，错误码是403。
 目前有两种处理情况： 1. 更改您的服务器验证处理，可以采取主动保护上述措施，中授权和主机请求头，这样无论是解决方案，知识都提供视频，而无需请求更新APP。 2. 我某些更改代码后该版本的 VLC 内核在某些时候会删除主机请求头，视频播放。IJK 和 EXO 内核无法进行更改，因为控制器的操作是内核内部处理，无法更改。
  
作者，你好，我也出现了这个问题，是否可以发我一个特殊版本呢？
  
可以，留一下邮箱或加我QQ

**Comment by MagmaBlock** [comment]
太良心了（
