### ISSUE TITLE
【远程媒体库】连接失败：密钥验证失败

### ISSUE THREAD

**Issue by SINC-G** [xyoye/DanDanPlayForAndroid#92]
**Bug描述**
打开远程媒体库出现 `连接失败：密钥验证失败`

**设备信息（请回答下列问题）：**
 - 设备：红米Note8Pro
 - OS：MIUI12.0.5，Android 10
 - 程序版本：PC端 11.4

**附加内容**
PC端更新11.4 之后出现的问题，如果设置API密钥则会出现 #88 中的问题

**Comment by xyoye** [comment]
请查看最新版
