### ISSUE TITLE
能否实现类似于mxplayer外挂其他字体文件夹来满足对字幕的字体需求？

### ISSUE THREAD

**Issue by YuukiHibiki** [xyoye/DanDanPlayForAndroid#93]
**您的功能请求是否与一个问题有关？请说明。**
app版无加载外挂字体的功能，会直接调用app字库
win版可以自动调用本地已有字体
**描述你所想要的解决方案**
希望能出一个选项指定字体文件夹，让视频字幕可以使用该文件夹的字体

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
