### ISSUE TITLE
文件页面字体大小不断变化

### ISSUE THREAD

**Issue by JeffersonQin** [xyoye/DanDanPlayForAndroid#96]
**Bug描述**

在文件页面，每上拉刷新一次，tableview cell内的字体大小就会发生变化

**如何重现**
重现该程序行为的步骤：见上

**屏幕截图**
![Screenshot_2021-08-21-02-06-11-343_com xyoye dandanplay](https://user-images.githubusercontent.com/30655701/130275543-a513c6ca-bca6-4144-8caf-b1f6aee3de49.jpg)

![Screenshot_2021-08-21-02-06-07-423_com xyoye dandanplay](https://user-images.githubusercontent.com/30655701/130275563-cac5013f-3c33-40a3-99bd-fdaa66fac4f4.jpg)

**设备信息（请回答下列问题）：**
 - 设备：小米 MIX 4
 - OS：MIUI 12.5
 - 程序版本：4.0.3

**Comment by xyoye** [comment]
请查看最新版
