### ISSUE TITLE
Tv播放页面的字幕和弹幕参数没法调

### ISSUE THREAD

**Issue by tianjiaoshanzai** [xyoye/DanDanPlayForAndroid#99]
**Bug描述**
播放页面点进去无法操作

**如何重现**
tv点进去视频，在播放页面点进去字幕和弹幕参数以及设置子页面，几乎无法点进去控制。

**希望的正确行为**
希望能点进去子页面默认“光标”出现在某处，便于操作。

**设备信息（请回答下列问题）：**

 - 设备：荣耀智慧屏X1
 - 程序版本：4.0.4

**Comment by xyoye** [comment]
由于问题太过久远，请更新至最新版本再试试，现在关闭此问题
